# NumPy

Read the links: https://numpy.org/doc/stable/user/quickstart.html  and https://numpy.org/doc/stable/user/basics.broadcasting.html  before solving the exercises. 

In [90]:
import numpy as np

### Print out the dimension (number of axes), shape, size and the datatype of the matrix A.

In [91]:
A = np.arange(1, 16).reshape(3,5)

print(A.ndim)
print(A.shape)
print(A.dtype)

2
(3, 5)
int32


### Do the following computations on the matrices B and C: 
* Elementwise subtraction. 
* Elementwise multiplication. 
* Matrix multiplication (by default you should use the @ operator).

In [92]:
B = np.arange(1, 10).reshape(3, 3)
C = np.ones((3, 3))*2

print(B)
print()
print(C)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]


In [93]:
B - C

array([[-1.,  0.,  1.],
       [ 2.,  3.,  4.],
       [ 5.,  6.,  7.]])

In [94]:
B * C

array([[ 2.,  4.,  6.],
       [ 8., 10., 12.],
       [14., 16., 18.]])

In [95]:
B @ C

array([[12., 12., 12.],
       [30., 30., 30.],
       [48., 48., 48.]])

### Do the following calculations on the matrix:
* Exponentiate each number elementwise (use the np.exp function).

* Calculate the minimum value in the whole matrix. 
* Calculcate the minimum value in each row. 
* Calculcate the minimum value in each column. 


* Find the index value for the minimum value in the whole matrix (hint: use np.argmin).
* Find the index value for the minimum value in each row (hint: use np.argmin).


* Calculate the sum for all elements.
* Calculate the mean for each column. 
* Calculate the median for each column. 

In [96]:
B = np.arange(1, 10).reshape(3, 3)
print(B)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [97]:
np.exp(B)

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02],
       [1.09663316e+03, 2.98095799e+03, 8.10308393e+03]])

In [98]:
np.min(B)

1

In [99]:
np.min(B, axis=1)

array([1, 4, 7])

In [100]:
np.min(B, axis=0)

array([1, 2, 3])

In [101]:
np.argmin(B)

0

In [102]:
np.argmin(B, axis=1)

array([0, 0, 0], dtype=int64)

In [103]:
np.sum(B)

45

In [104]:
np.mean(B, axis=0)

array([4., 5., 6.])

In [105]:
np.median(B, axis=0)

array([4., 5., 6.])

### What does it mean when you provide fewer indices than axes when slicing? See example below.

In [106]:
print(A)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [107]:
A[1]

array([ 6,  7,  8,  9, 10])

**Answer:**

The missing indices are complete slices. In the above example, A[1] is equivalent to A[1, :].

### Iterating over multidimensional arrays is done with respect to the first axis, so in the example below we iterate trough the rows. If you would like to iterate through the array *elementwise*, how would you do that?

In [108]:
A

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [109]:
for i in A:
    print(i)

[1 2 3 4 5]
[ 6  7  8  9 10]
[11 12 13 14 15]


In [110]:
for i in A.flat:
    print(i)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15


### Explain what the code below does. More specifically, b has three axes - what does this mean? 

In [111]:
a = np.arange(30)
b = a.reshape((2, 3, -1))
print(a)
print()

print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]


Line 1 returns an array of 30 elements in one axis.
Line 2 reshapes the array to three dimensions, with, respectively, two and three elements on the first two axes, the number of elements on the third axis, given as -1, is automatically calculated.

### Broadcasting
**Read the following link about broadcasting: https://numpy.org/doc/stable/user/basics.broadcasting.html#basics-broadcasting**

# Remark on Broadcasting when doing Linear Algebra calculations in Python. 

### From the mathematical rules of matrix addition, the operation below (m1 + m2) does not make sense. The reason is that matrix addition requires two matrices of the same size. In Python however, it works due to broadcasting rules in NumPy. So you must be careful when doing Linear Algebra calculations in Python since they do not follow the "mathematical rules". This can however easily be handled by doing some simple programming, for example validating that two matrices have the same shape is easy if you for instance want to add two matrices. 

In [112]:
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([1, 1])
print(m1 + m2)

[[2 3]
 [4 5]]


### The example below would also not be allowed if following the "mathematical rules" in Linear Algebra. But it works due to broadcasting in NumPy. 

In [113]:
v1 = np.array([1, 2, 3])
print(v1 + 1)

[2 3 4]


In [114]:
A = np.arange(1, 5).reshape(2,2)
print(A)

b = np.array([2, 2])
print(b)

[[1 2]
 [3 4]]
[2 2]


**Now you are going to create a function that can be reused every time you add or multiply matrices. The function is created so that we do the addition and multiplication according to the rules of vector- and matrix algebra.**

**Create a function "add_mult_matrices" that takes two matrices as input arguments (validate that the input are of the type numpy.ndarray by using the isinstance function), a third argument that is either 'add' or 'multiply' that specifies if you want to add or multiply the matrices (validate that the third argument is either 'add' or 'multiply'). When doing matrix addition, validate that the matrices have the same size. When doing matrix multiplication, validate that the sizes conform (i.e. number of columns in the first matrix is equal to the number of rows in the second matrix).**

# Vector- and matrix algebra Exercises

In [129]:
import numpy as np

def add_mult_matrices(A, B, add_mult):
    A = np.array(A)
    B = np.array(B)
    
    # Validation with isinstance was asked for but is redundant because the input is converted to numpy array.
    if not isinstance(A, np.ndarray):
        return 'A is not a numpy array'
    if not isinstance(B, np.ndarray):
        return 'B is not a numpy array'
    
    if add_mult == 'add' and A.shape != B.shape:
        print('Matrices must be of the same shape to add')
    elif add_mult == 'add':        
        return A + B
    elif add_mult == 'multiply' and A.shape[1] != B.shape[0]:
        return 'Number of columns in A must be equal to the number of rows in B to multiply'
    elif add_mult == 'multiply':
        return A @ B
    else:
        return 'Choose add or multiply'

A = [[1, 2], [3, 4]]
B = [[2, 3], [4, 5]]
add_mult = 'add'

print(add_mult_matrices(A, B, add_mult))

[[3 5]
 [7 9]]


### Solve all the exercises in chapter 10.1 in the book "Matematik för yrkeshögskolan". 

**10.1.1.** \
Definiera vektorn $ \vec{x} $ enligt nedan.
>$ \vec{x} = (4, 3) $

- a) Vilken dimension har vektorn $ \vec{x} $?
- b) Beräkna $ 5 \vec{x} $
- c) Beräkna $ 3 \vec{x} $
- d) Beräkna $ 5 \vec{x} + 3 \vec{x} $
- e) Beräkna $ 8 \vec{x} $
- f) Beräkna $ 4 \vec{x} - \vec{x} $
- g) Beräkna $ \vec{x}^T $, vilken blir den nya dimensionen efter att transponeringen utförts?
- h) Är $ \vec{x} + \vec{x}^T $ definierat?
- i) Beräkna $ ||\vec{x}|| $
        

a) (1x2)

In [116]:
x = np.array([4, 3])
x.shape

(2,)

b) $ 5 \vec{x} = 5(4, 3) = (20, 15) $

In [117]:
5 * x

array([20, 15])

c) $ 3 \vec{x} = 3(4, 3) = (12, 9) $

In [118]:
3 * x

array([12,  9])

d) $ 5 \vec{x} + 3 \vec{x} = (20, 15) - (12, 9) = (32, 24) $

In [119]:
5 * x + 3 * x

array([32, 24])

e) $ 8 \vec{x} = 8(4, 3) = (32, 24) $

In [120]:
8 * x

array([32, 24])

f) $ 4 \vec{x} - \vec{x} = 4(4, 3) - (4, 3) = (16, 12) - (4, 3) = (12, 9) $

In [121]:
4 * x - x

array([12,  9])

g) (2x1) \
$ \vec{x^T} = \begin{bmatrix}
4 \\
3
\end{bmatrix} $

In [127]:
y = x.T
print(y)

[4 3]


h) $ \vec{x} + \vec{x}^T $ är inte definierat.

i) $ ||\vec{x}|| =  \sqrt{4^2 + 3^2} = \sqrt{16 + 9} = 5 $

In [128]:
np.linalg.norm(x)

5.0

**10.1.2.** \
Definiera vektorn $ \vec{v} $ enligt nedan. \
$ \vec{v} = \begin{bmatrix}
3 \\
7 \\
0 \\
11
\end{bmatrix} $
- a) Vilken dimension har vektorn $ \vec{v} $?
- b) Beräkna $ 2 \vec{v} $
- c) Beräkna $ 5 \vec{v} + 2 \vec{v} $
- d) Beräkna $ 4 \vec{v} - 2 \vec{v} $
- e) Beräkna $ \vec{v}^T $. vilken blir den nya dimensionen efter att transponeringen utförts?
- f) Beräkna $ || \vec{v} || $




a) (4x1)

In [132]:
v = np.array([3, 7, 0, 11])
v.reshape(4, 1)

array([[ 3],
       [ 7],
       [ 0],
       [11]])

b) $ 2 \vec{v} = \begin{bmatrix}
6 \\
14 \\
0 \\
22
\end{bmatrix} $

In [133]:
2 * v

array([ 6, 14,  0, 22])

c) $ 5 \vec{v} + 2 \vec{v} = 5 \begin{bmatrix}
3 \\
7 \\
0 \\
11
\end{bmatrix} + 2 \begin{bmatrix}
3 \\
7 \\
0 \\
11
\end{bmatrix} = \begin{bmatrix}
21 \\
49 \\
0 \\
77
\end{bmatrix}
$

In [134]:
5 * v + 2 * v

array([21, 49,  0, 77])

d) $ 4 \vec{v} - 2 \vec{v} = 4 \begin{bmatrix}
3 \\
7 \\
0 \\
11
\end{bmatrix} - 2 \begin{bmatrix}
3 \\
7 \\
0 \\
11
\end{bmatrix} = \begin{bmatrix}
12 \\
28 \\
0 \\
44
\end{bmatrix} - \begin{bmatrix}
6 \\
14 \\
0 \\
22 
\end{bmatrix} = \begin{bmatrix}
6 \\
14 \\
0 \\
22
\end{bmatrix}
$

In [135]:
4 * v - 2 * v

array([ 6, 14,  0, 22])

e) $ \vec{v}^T = (3, 7, 0, 11) $, dimensionen (1x4)

In [137]:
z = v.T
print(z)

[ 3  7  0 11]


f) $ || \vec{v} || = \sqrt{3^2 + 7^2 + 0^2 + 11^2} = \sqrt{9 + 49 + 121} = \sqrt{179}  \approx{13.38}$

In [138]:
np.linalg.norm(v)

13.379088160259652

### Solve all the exercises, except 10.2.4, in chapter 10.2 in the book "Matematik för yrkeshögskolan". 

### Copies and Views
Read the following link: https://numpy.org/doc/stable/user/basics.copies.html

**Basic indexing creates a view, How can you check if v1 and v2 is a view or copy? If you change the last element in v2 to 123, will the last element in v1 be changed? Why?**

In [ ]:
v1 = np.arange(4)
v2 = v1[-2:]
print(v1)
print(v2)

In [ ]:
# The base attribute of a view returns the original array while it returns None for a copy.
print(v1.base)
print(v2.base)

In [ ]:
# The last element in v1 will be changed aswell since v2 is a view, meaning they share the same data buffer.
v2[-1] = 123
print(v1)
print(v2)