In [1]:
import numpy as np

In [4]:
a = np.array([2, 3, 4])
a

array([2, 3, 4])

In [5]:
a.dtype

dtype('int32')

In [6]:
b = np.array([1.2, 3.5, 5.1])
b.dtype

dtype('float64')

In [9]:
b = np.array([(1.5, 2, 3), (4, 5, 6)])
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [12]:
c = np.array([[1, 2], [3, 4]], dtype=complex)
c

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

In [13]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [14]:
np.ones((2, 3, 4), dtype=np.int16)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [22]:
np.empty((2, 3))

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [23]:
np.arange(10, 30, 5)

array([10, 15, 20, 25])

In [24]:
np.arange(0, 2, 0.3)

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

In [25]:
from numpy import pi
np.linspace(0, 2, 9)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [27]:
x = np.linspace(0, 2*pi, 100)
f = np.sin(x)

In [29]:
rng = np.random.default_rng()
rng.random()

0.6952267401043493

In [31]:
rng.random(5)

array([0.73586759, 0.2964748 , 0.64367729, 0.55398321, 0.27330583])

In [32]:
5 * rng.random((3, 2)) - 5

array([[-3.26996771, -2.92291724],
       [-3.10543072, -1.53758601],
       [-1.20035735, -0.65592075]])

In [37]:
rng = np.random.default_rng()
rng.integers(100, size = 10)

array([47, 86, 65, 47, 54,  1, 92, 86, 77, 16], dtype=int64)

In [44]:
rng.integers(1, [3, 5, 7, 9])

array([1, 3, 2, 5], dtype=int64)

In [45]:
rng.integers(100, size=(3, 10))

array([[96, 74,  1, 69, 38, 97, 90, 42, 84, 94],
       [36, 73, 88, 93, 31, 90, 54, 41, 26, 93],
       [69, 98, 62, 38, 19, 54, 97, 25,  8, 99]], dtype=int64)

In [46]:
a = np.arange(6)
print(a)

[0 1 2 3 4 5]


In [48]:
b = np.arange(12).reshape(4, 3)
print(b)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [49]:
c = np.arange(24).reshape(2, 3, 4)
print(c)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [50]:
print(np.arange(7586))

[   0    1    2 ... 7583 7584 7585]


In [52]:
print(np.arange(6000).reshape(100, 60))

[[   0    1    2 ...   57   58   59]
 [  60   61   62 ...  117  118  119]
 [ 120  121  122 ...  177  178  179]
 ...
 [5820 5821 5822 ... 5877 5878 5879]
 [5880 5881 5882 ... 5937 5938 5939]
 [5940 5941 5942 ... 5997 5998 5999]]


In [53]:
a = np.array([20, 30, 40, 50])
b = np.arange(4)
b

array([0, 1, 2, 3])

In [54]:
c = a - b
c

array([20, 29, 38, 47])

In [55]:
b**2

array([0, 1, 4, 9])

In [56]:
10 * np.sin(a)

array([ 9.12945251, -9.88031624,  7.4511316 , -2.62374854])

In [57]:
a < 35

array([ True,  True, False, False])